spring:
  application:
    name: profile-service-api
  data:
    mongodb:
      database: profile
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    data: classpath:test.sql
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:~/profile
    username: root
    password: root

kafka:
  broker:
    urls: localhost:9092
  producer:
    business-profile-update:
      topic: business-profile-update

resilience4j:
  ratelimiter:
    instances:
      profileUpdate:
        limit-refresh-period: 10s
        limit-for-period: 1
        writableStackTraceEnabled: true